### ISSUE TITLE
UDP Send to all but

### ISSUE THREAD

**Issue by kirill-782** [uakfdotb/gcb#38]
Can you add the UDP black list function to the recipients? I think you can do so that some kind of user did not receive the package? Or tell me where to patch

**Comment by kirill-782** [comment]
Not actual

**Comment by uakfdotb** [comment]
Did you figure this out?

* If you are using gcb_broadcastfilter_key and gcb_broadcastfilter_cache: https://github.com/uakfdotb/gcb/blob/master/src/gcb/WC3Interface.java#L179 (when it replies to the W3GS_SEARCHGAME sent by player)
* Otherwise, WC3Interface uses the GarenaInterface.broadcastUDPEncap function (https://github.com/uakfdotb/gcb/blob/master/src/gcb/WC3Interface.java#L422 and https://github.com/uakfdotb/gcb/blob/master/src/gcb/GarenaInterface.java#L1918)

Changing the latter is simple, just add an if statement in the broadcastUDPEncap loop to skip the specific users you don't want to send UDP packets too.

You could modify the first case in GarenaInterface as well, modify sendUDPEncap:
* Scan this.members for MemberInfo objects where the external IP or internal IP matches address parameter
* If any matching members are on the blacklist, then return from the function and don't send the packet

**Comment by kirill-782** [comment]
@uakfdotb
Can I contact you in some kind of chat or Skype?

**Comment by styla01** [comment]
@uakfdotb Can you help us with some hints?

**Comment by uakfdotb** [comment]
What do you want to filter by? Username, user ID, etc.?

**Comment by uakfdotb** [comment]
For example if you want to do by username, you can modify these functions in GarenaInterface.java to look like below (say you don't want to send to username "AntiGcbBot"):

	public void broadcastUDPEncap(int source, int destination, byte[] data, int offset, int length) {
		synchronized(members) {
			for(MemberInfo target : members) {
				if(target.userID == this.user_id) continue;
				if(!target.playing) continue; //don't broadcast if they don't have WC3 open
				if(target.username.equalsIgnoreCase("AntiGcbBot")) continue;

				if(target.correctIP == null) {
					//send on both external and internal
					sendUDPEncap(target.externalIP, target.externalPort, source, destination, data, offset, length);
					sendUDPEncap(target.internalIP, target.internalPort, source, destination, data, offset, length);
				} else {
					sendUDPEncap(target.correctIP, target.correctPort, source, destination, data, offset, length);
				}
			}
		}
	}

	public void sendUDPEncap(InetAddress address, int port, int source, int destination, byte[] data, int offset, int length) {
		for(MemberInfo target : members) {
			if((target.externalIP != null && target.externalIP.equals(address) || (target.internalIP != null && target.internalIP.equals(address)) || (target.correctIP != null && target.correctIP.equals(address))) {
				if(target.username.equalsIgnoreCase("AntiGcbBot")) return;
			}
		}
		ByteBuffer lbuf = ByteBuffer.allocate(length + 16);
		lbuf.order(ByteOrder.LITTLE_ENDIAN);
		lbuf.put(0, (byte) 0x01);
		lbuf.putInt(4, user_id);
		lbuf.order(ByteOrder.BIG_ENDIAN);
		lbuf.putShort(8, (short) source);
		lbuf.putShort(12, (short) destination);
		lbuf.position(16);
		lbuf.put(data, offset, length);

		byte[] array = lbuf.array();
		DatagramPacket packet = new DatagramPacket(array, array.length, address, port);

		try {
			peer_socket.send(packet);
		} catch(IOException ioe) {
			//ioe.printStackTrace();
		}
	}

**Comment by kirill-782** [comment]
@uakfdotb
here we decided.
It happens that with a weak connection, packets are lost and do not reach the recipient at all

**Comment by uakfdotb** [comment]
I thought you are asking whether you can have blacklist to avoid sending packets to a particular user.

**Comment by kirill-782** [comment]
https://github.com/uakfdotb/gcb/issues/26 
here is the problem, but some of the comments have disappeared somewhere

**Comment by kirill-782** [comment]
I will investigate the problem in more detail and send a report
